# top folder where ntuples live with the structure
# ntuple_path/SAMPLE/SYSTEMATIC.root
ntuple_path: "/Users/khoo/Work/ATLAS/Helena_Masters/HH4b_JZ2to4_bfilt4j15/"
results_path: "/Users/khoo/Work/ATLAS/Helena_Masters/tomatos_out/"

# name of NOSYS.root holding the nominal non-systematic values
nominal: NOSYS
tree_name: AnalysisMiniTree
signal_sample: "Signal"
# total events that are batched in training from all sample_sys combined
# 1e7 with 20 vars ~1.6 GB in memory
batch_size: 134672

# the main data array is defined by (n_samples, n_events, vars)
vars:
  - "j1_pt"
  - "j2_pt"
  - "j1_mass"
  - "j2_mass"
  - "m_hh"
event_weight_var: weight
aux_vars:
  - "j1_tag"
  - "j2_tag"

# Pre-trained model
pretrain_params: "/Users/khoo/Work/ATLAS/Helena_Masters/tomatos_out/tomatos_bce_steps_250_bins_8_SMHH_JZ1to4_fixNtag/models/epoch_best.eqx"

# ratio need to add up to one
train_ratio: 0.8
valid_ratio: 0.1
test_ratio: 0.1

plot_inputs: True

# bce, cls_nn, cls_var (bins, cuts) in some variable
# might drop bce, needs some attention currently
objective: "cls_nn"
# you can speed up cls_var, if you only setup the var and the cut_vars in
cls_var: "m_hh"

n_bins: 8
# includes bin edges in optimization, not necessary for cls_nn
include_bins: false
# results folder suffix
suffix: "SMHH_JZ1to4_pretrain"
# train steps
num_steps: 250
# how often to print status
# learning rate
lr: 0.003
# can choose from linear_cycle, constant
lr_schedule: "linear_cycle"
# start and minimum value for the bandwidth adaptation
bw_init: 0.25
bw_min: 0.02
# slope value in the sigmoid, this is pretty sharp!
slope: 150
# need to limit these updates to avoid gradient explosion
update_limit_bw: 0.005
update_limit_cuts: 0.0005 # for min max scaled between (0,1)

# cuts on vars to be optimized, keep variables either "above", "below"
# or below, start somewhere where the cut actually does something to
# find a gradient
# NOTE: values must be min-max scaled between (0, 1), not raw values!
opt_cuts:
  j1_pt:
    keep: "above" # or below
    init: 200_000
  j2_pt:
    keep: "above" 
    init: 100_000

# applies a scale factor to the histograms accordingly
n_k_folds: 0.2

# skip frames by modulo for movie
movie_batch_modulo: 1
